/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

/**
 *
 * @author cindy
 */
public class MetodoSimplex extends javax.swing.JPanel {

    /**
     * Creates new form SimplexMaxi
     */
    public MetodoSimplex() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtRX1 = new javax.swing.JTextField();
        txtRX2 = new javax.swing.JTextField();
        txtRY1 = new javax.swing.JTextField();
        txtRY2 = new javax.swing.JTextField();
        txtRS3 = new javax.swing.JTextField();
        txtRS1 = new javax.swing.JTextField();
        txtRS2 = new javax.swing.JTextField();
        txtRZ3 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtRZ1 = new javax.swing.JTextField();
        txtRZ2 = new javax.swing.JTextField();
        btnLimpiar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel18 = new javax.swing.JLabel();
        btnMinimizar = new javax.swing.JButton();
        btnMaximizar = new javax.swing.JButton();
        txtRespuesta = new javax.swing.JTextField();
        txtEX1 = new javax.swing.JTextField();
        txtEX3 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtEX2 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtTipo = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtEX4 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(230, 230, 230));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(txtRX1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 90, 40, -1));
        add(txtRX2, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 130, 40, -1));

        txtRY1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRY1ActionPerformed(evt);
            }
        });
        add(txtRY1, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 90, 50, -1));
        add(txtRY2, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 120, 50, -1));

        txtRS3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRS3ActionPerformed(evt);
            }
        });
        add(txtRS3, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 150, 50, -1));

        txtRS1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRS1ActionPerformed(evt);
            }
        });
        add(txtRS1, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 90, 50, -1));

        txtRS2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRS2ActionPerformed(evt);
            }
        });
        add(txtRS2, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 120, 50, -1));

        txtRZ3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRZ3ActionPerformed(evt);
            }
        });
        add(txtRZ3, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 160, 50, 20));

        jLabel7.setText("X");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 90, -1, -1));

        jLabel8.setText("X");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 130, -1, -1));

        jLabel9.setText("+");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 90, 20, -1));

        jLabel10.setText("Y");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 90, 10, -1));

        jLabel11.setText("Y");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 120, 20, -1));

        jLabel12.setText("X, Y");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 160, -1, -1));

        jLabel13.setText("+");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 130, -1, -1));
        add(txtRZ1, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 90, 50, -1));
        add(txtRZ2, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 120, 50, -1));

        btnLimpiar.setBackground(new java.awt.Color(204, 204, 204));
        btnLimpiar.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        btnLimpiar.setForeground(new java.awt.Color(33, 48, 71));
        btnLimpiar.setText("LIMPIAR");
        btnLimpiar.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(33, 48, 71), null));
        btnLimpiar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 100, 30));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Variables básicas", "Ecuación", "X1", "X2", "X3", "X4", "X5", "Lado derecho"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 900, 260));

        jSeparator1.setBackground(new java.awt.Color(33, 48, 71));
        jSeparator1.setForeground(new java.awt.Color(33, 48, 71));
        jSeparator1.setOpaque(true);
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 10, 980, 2));

        jSeparator3.setBackground(new java.awt.Color(33, 48, 71));
        jSeparator3.setForeground(new java.awt.Color(33, 48, 71));
        jSeparator3.setOpaque(true);
        add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(942, -7, 2, 700));

        jSeparator2.setBackground(new java.awt.Color(33, 48, 71));
        jSeparator2.setForeground(new java.awt.Color(33, 48, 71));
        jSeparator2.setOpaque(true);
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 663, 980, 2));

        jLabel18.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(33, 48, 71));
        jLabel18.setText("Restricciones");
        add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 50, -1, -1));

        btnMinimizar.setBackground(new java.awt.Color(204, 204, 204));
        btnMinimizar.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        btnMinimizar.setForeground(new java.awt.Color(33, 48, 71));
        btnMinimizar.setText("MINIMIZAR");
        btnMinimizar.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(33, 48, 71), null));
        btnMinimizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMinimizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinimizarActionPerformed(evt);
            }
        });
        add(btnMinimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 100, 30));

        btnMaximizar.setBackground(new java.awt.Color(204, 204, 204));
        btnMaximizar.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        btnMaximizar.setForeground(new java.awt.Color(33, 48, 71));
        btnMaximizar.setText("MAXIMIZAR");
        btnMaximizar.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(33, 48, 71), null));
        btnMaximizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMaximizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMaximizarActionPerformed(evt);
            }
        });
        add(btnMaximizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, 100, 30));

        txtRespuesta.setBackground(new java.awt.Color(204, 204, 204));
        txtRespuesta.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        txtRespuesta.setForeground(new java.awt.Color(33, 48, 71));
        txtRespuesta.setBorder(null);
        add(txtRespuesta, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 540, 290, 25));

        txtEX1.setBackground(new java.awt.Color(204, 204, 204));
        txtEX1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        txtEX1.setForeground(new java.awt.Color(33, 48, 71));
        txtEX1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtEX1.setBorder(null);
        add(txtEX1, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 110, 50, 25));

        txtEX3.setBackground(new java.awt.Color(204, 204, 204));
        txtEX3.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        txtEX3.setForeground(new java.awt.Color(33, 48, 71));
        txtEX3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtEX3.setBorder(null);
        add(txtEX3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 110, 50, 25));

        jLabel23.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(33, 48, 71));
        jLabel23.setText("X1   +");
        add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 50, 25));

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(33, 48, 71));
        jLabel1.setText("Ecuación");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, -1, -1));

        txtEX2.setBackground(new java.awt.Color(204, 204, 204));
        txtEX2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        txtEX2.setForeground(new java.awt.Color(33, 48, 71));
        txtEX2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtEX2.setBorder(null);
        add(txtEX2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, 50, 25));

        jLabel15.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(33, 48, 71));
        jLabel15.setText("X4");
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 110, 40, 25));

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(33, 48, 71));
        jLabel2.setText("MÉTODO SIMPLEX ");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, -1, 25));

        txtTipo.setBackground(new java.awt.Color(230, 230, 230));
        txtTipo.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        txtTipo.setForeground(new java.awt.Color(33, 48, 71));
        txtTipo.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtTipo.setBorder(null);
        add(txtTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 50, 190, 25));

        jLabel17.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(33, 48, 71));
        jLabel17.setText("RESPUESTA");
        add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 520, -1, -1));

        jLabel16.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(33, 48, 71));
        jLabel16.setText("X2   +");
        add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 110, 40, 25));

        txtEX4.setBackground(new java.awt.Color(204, 204, 204));
        txtEX4.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        txtEX4.setForeground(new java.awt.Color(33, 48, 71));
        txtEX4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtEX4.setBorder(null);
        add(txtEX4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 110, 50, 25));

        jLabel19.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(33, 48, 71));
        jLabel19.setText("X3   +");
        add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 110, 40, 25));
    }// </editor-fold>//GEN-END:initComponents

    private void txtRS3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRS3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRS3ActionPerformed

    private void txtRS2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRS2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRS2ActionPerformed

    private void txtRY1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRY1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRY1ActionPerformed

    private void txtRS1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRS1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRS1ActionPerformed

    private void txtRZ3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRZ3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRZ3ActionPerformed

    private void btnMinimizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinimizarActionPerformed
        txtTipo.setText(" - MINIMIZAR");
    }//GEN-LAST:event_btnMinimizarActionPerformed

    private void btnMaximizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMaximizarActionPerformed
        txtTipo.setText(" - MAXIMIZAR");
    }//GEN-LAST:event_btnMaximizarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnMaximizar;
    private javax.swing.JButton btnMinimizar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtEX1;
    private javax.swing.JTextField txtEX2;
    private javax.swing.JTextField txtEX3;
    private javax.swing.JTextField txtEX4;
    private javax.swing.JTextField txtRS1;
    private javax.swing.JTextField txtRS2;
    private javax.swing.JTextField txtRS3;
    private javax.swing.JTextField txtRX1;
    private javax.swing.JTextField txtRX2;
    private javax.swing.JTextField txtRY1;
    private javax.swing.JTextField txtRY2;
    private javax.swing.JTextField txtRZ1;
    private javax.swing.JTextField txtRZ2;
    private javax.swing.JTextField txtRZ3;
    public javax.swing.JTextField txtRespuesta;
    private javax.swing.JTextField txtTipo;
    // End of variables declaration//GEN-END:variables
}
