/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

/**
 *
 * @author cindy
 */
public class MetodoGrafico extends javax.swing.JPanel {

    /**
     * Creates new form GraficaMaxi
     */
    public MetodoGrafico() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtEX = new javax.swing.JTextField();
        txtEY = new javax.swing.JTextField();
        txtRX1 = new javax.swing.JTextField();
        txtRY1 = new javax.swing.JTextField();
        txtRZ1 = new javax.swing.JTextField();
        txtRS1 = new javax.swing.JTextField();
        txtRX2 = new javax.swing.JTextField();
        txtRY2 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtRS2 = new javax.swing.JTextField();
        txtRZ2 = new javax.swing.JTextField();
        txtRS3 = new javax.swing.JTextField();
        txtRZ3 = new javax.swing.JTextField();
        btnMinimizar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtPX1 = new javax.swing.JTextField();
        txtPX2 = new javax.swing.JTextField();
        txtPX3 = new javax.swing.JTextField();
        txtPX4 = new javax.swing.JTextField();
        txtPY1 = new javax.swing.JTextField();
        txtPY2 = new javax.swing.JTextField();
        txtPY3 = new javax.swing.JTextField();
        txtPY4 = new javax.swing.JTextField();
        txtPZ1 = new javax.swing.JTextField();
        txtPZ2 = new javax.swing.JTextField();
        txtPZ3 = new javax.swing.JTextField();
        txtPZ4 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtRespuesta = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        btnMaximizar = new javax.swing.JButton();
        txtTipo = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(230, 230, 230));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(33, 48, 71));
        jLabel1.setText("Ecuación:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, -1, -1));

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(33, 48, 71));
        jLabel2.setText("MÉTODO GRÁFICO ");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, -1, 25));

        jLabel3.setText("X");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, -1, -1));

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(33, 48, 71));
        jLabel4.setText("Restricciones");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 60, -1, -1));

        jLabel5.setText("+");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 130, -1, -1));

        jLabel6.setText("X");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 170, 10, -1));
        add(txtEX, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 50, -1));
        add(txtEY, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, 60, -1));
        add(txtRX1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 130, 50, -1));
        add(txtRY1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 130, 40, -1));
        add(txtRZ1, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 130, 60, -1));
        add(txtRS1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 130, 60, -1));
        add(txtRX2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 170, 50, -1));
        add(txtRY2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 170, 40, -1));

        jLabel7.setText("X");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 130, -1, -1));

        jLabel8.setText("Y");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 80, 20, -1));

        jLabel9.setText("+");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, 20, 20));

        jLabel10.setText("Y");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 130, 10, -1));

        jLabel11.setText("+");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 170, 10, -1));

        jLabel12.setText("Y");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 170, 10, -1));

        jLabel13.setText("X , Y");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 200, -1, -1));
        add(txtRS2, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 170, 60, -1));
        add(txtRZ2, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 170, 60, -1));
        add(txtRS3, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 200, 60, -1));
        add(txtRZ3, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 200, 60, -1));

        btnMinimizar.setBackground(new java.awt.Color(204, 204, 204));
        btnMinimizar.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        btnMinimizar.setForeground(new java.awt.Color(33, 48, 71));
        btnMinimizar.setText("MINIMIZAR");
        btnMinimizar.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(33, 48, 71), null));
        btnMinimizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMinimizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinimizarActionPerformed(evt);
            }
        });
        add(btnMinimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 100, 30));

        btnLimpiar.setBackground(new java.awt.Color(204, 204, 204));
        btnLimpiar.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        btnLimpiar.setForeground(new java.awt.Color(33, 48, 71));
        btnLimpiar.setText("LIMPIAR");
        btnLimpiar.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(33, 48, 71), null));
        btnLimpiar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 100, 30));
        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 550, 410));

        jLabel14.setText("X");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 290, -1, -1));

        jLabel15.setText("Y");
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 290, -1, -1));

        jLabel16.setText("Z");
        add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 290, -1, -1));
        add(txtPX1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 320, 50, -1));
        add(txtPX2, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 350, 50, -1));
        add(txtPX3, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 390, 50, -1));
        add(txtPX4, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 430, 50, -1));

        txtPY1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPY1ActionPerformed(evt);
            }
        });
        add(txtPY1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 320, 50, -1));
        add(txtPY2, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 350, 50, -1));

        txtPY3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPY3ActionPerformed(evt);
            }
        });
        add(txtPY3, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 390, 50, -1));

        txtPY4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPY4ActionPerformed(evt);
            }
        });
        add(txtPY4, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 430, 50, -1));
        add(txtPZ1, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 320, 50, -1));
        add(txtPZ2, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 350, 50, -1));
        add(txtPZ3, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 390, 50, -1));
        add(txtPZ4, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 430, 50, -1));

        jLabel17.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(33, 48, 71));
        jLabel17.setText("RESPUESTA");
        add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 510, -1, -1));
        add(txtRespuesta, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 540, 190, -1));

        jLabel18.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(33, 48, 71));
        jLabel18.setText("Puntos de Intersección");
        add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 270, -1, -1));

        btnMaximizar.setBackground(new java.awt.Color(204, 204, 204));
        btnMaximizar.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        btnMaximizar.setForeground(new java.awt.Color(33, 48, 71));
        btnMaximizar.setText("MAXIMIZAR");
        btnMaximizar.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(33, 48, 71), null));
        btnMaximizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMaximizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMaximizarActionPerformed(evt);
            }
        });
        add(btnMaximizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, 100, 30));

        txtTipo.setBackground(new java.awt.Color(230, 230, 230));
        txtTipo.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        txtTipo.setForeground(new java.awt.Color(33, 48, 71));
        txtTipo.setBorder(null);
        add(txtTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 40, 130, 25));

        jSeparator1.setBackground(new java.awt.Color(33, 48, 71));
        jSeparator1.setForeground(new java.awt.Color(33, 48, 71));
        jSeparator1.setOpaque(true);
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 10, 980, 2));

        jSeparator2.setBackground(new java.awt.Color(33, 48, 71));
        jSeparator2.setForeground(new java.awt.Color(33, 48, 71));
        jSeparator2.setOpaque(true);
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 663, 980, 2));

        jSeparator3.setBackground(new java.awt.Color(33, 48, 71));
        jSeparator3.setForeground(new java.awt.Color(33, 48, 71));
        jSeparator3.setOpaque(true);
        add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(942, -7, 2, 700));
    }// </editor-fold>//GEN-END:initComponents

    private void txtPY1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPY1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPY1ActionPerformed

    private void txtPY3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPY3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPY3ActionPerformed

    private void txtPY4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPY4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPY4ActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        txtEX.setText("");
        txtEY.setText("");

        txtRX1.setText("");
        txtRX2.setText("");
        txtRY1.setText("");
        txtRY2.setText("");
        txtRS1.setText("");
        txtRS2.setText("");
        txtRS3.setText("");
        txtRZ1.setText("");
        txtRZ2.setText("");
        txtRZ3.setText("");

        txtPX1.setText("");
        txtPX2.setText("");
        txtPX3.setText("");
        txtPX4.setText("");
        txtPY1.setText("");
        txtPY2.setText("");
        txtPY3.setText("");
        txtPY4.setText("");
        txtPZ1.setText("");
        txtPZ2.setText("");
        txtPZ3.setText("");
        txtPZ4.setText("");

        txtRespuesta.setText("");
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnMinimizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinimizarActionPerformed
        txtTipo.setText(" - MINIMIZAR");
    }//GEN-LAST:event_btnMinimizarActionPerformed

    private void btnMaximizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMaximizarActionPerformed
        txtTipo.setText(" - MAXIMIZAR");
    }//GEN-LAST:event_btnMaximizarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnMaximizar;
    private javax.swing.JButton btnMinimizar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField txtEX;
    private javax.swing.JTextField txtEY;
    private javax.swing.JTextField txtPX1;
    private javax.swing.JTextField txtPX2;
    private javax.swing.JTextField txtPX3;
    private javax.swing.JTextField txtPX4;
    private javax.swing.JTextField txtPY1;
    private javax.swing.JTextField txtPY2;
    private javax.swing.JTextField txtPY3;
    private javax.swing.JTextField txtPY4;
    private javax.swing.JTextField txtPZ1;
    private javax.swing.JTextField txtPZ2;
    private javax.swing.JTextField txtPZ3;
    private javax.swing.JTextField txtPZ4;
    private javax.swing.JTextField txtRS1;
    private javax.swing.JTextField txtRS2;
    private javax.swing.JTextField txtRS3;
    private javax.swing.JTextField txtRX1;
    private javax.swing.JTextField txtRX2;
    private javax.swing.JTextField txtRY1;
    private javax.swing.JTextField txtRY2;
    private javax.swing.JTextField txtRZ1;
    private javax.swing.JTextField txtRZ2;
    private javax.swing.JTextField txtRZ3;
    private javax.swing.JTextField txtRespuesta;
    private javax.swing.JTextField txtTipo;
    // End of variables declaration//GEN-END:variables
}
