/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

/**
 *
 * @author cindy
 */
public class SimplexMaxi extends javax.swing.JPanel {

    /**
     * Creates new form SimplexMaxi
     */
    public SimplexMaxi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtEX1 = new javax.swing.JTextField();
        txtEX2 = new javax.swing.JTextField();
        txtX3 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtRX1 = new javax.swing.JTextField();
        txtRX2 = new javax.swing.JTextField();
        txtRY1 = new javax.swing.JTextField();
        txtRY2 = new javax.swing.JTextField();
        txtRS3 = new javax.swing.JTextField();
        txtRS1 = new javax.swing.JTextField();
        txtRS2 = new javax.swing.JTextField();
        txtRZ3 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtRZ1 = new javax.swing.JTextField();
        txtRZ2 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        btnLimpiar = new javax.swing.JButton();
        btnResolver = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(230, 230, 230));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("MÉTODO SIMPLEX MAXIMIZACIÓN");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, -1, -1));

        jLabel2.setText("Ecuación:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        txtEX1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEX1ActionPerformed(evt);
            }
        });
        add(txtEX1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 50, -1));
        add(txtEX2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, 60, -1));
        add(txtX3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 70, -1, -1));

        jLabel3.setText("X1");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, -1, -1));

        jLabel4.setText("X2");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, -1, -1));

        jLabel5.setText("X3");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 70, -1, -1));

        jLabel6.setText("Restricciones");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 60, -1, 20));
        add(txtRX1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 90, 40, -1));
        add(txtRX2, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 130, 40, -1));

        txtRY1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRY1ActionPerformed(evt);
            }
        });
        add(txtRY1, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 90, 50, -1));
        add(txtRY2, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 120, 50, -1));

        txtRS3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRS3ActionPerformed(evt);
            }
        });
        add(txtRS3, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 150, 50, -1));

        txtRS1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRS1ActionPerformed(evt);
            }
        });
        add(txtRS1, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 90, 50, -1));

        txtRS2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRS2ActionPerformed(evt);
            }
        });
        add(txtRS2, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 120, 50, -1));

        txtRZ3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRZ3ActionPerformed(evt);
            }
        });
        add(txtRZ3, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 160, 50, 20));

        jLabel7.setText("X");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 90, -1, -1));

        jLabel8.setText("X");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 130, -1, -1));

        jLabel9.setText("+");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 90, 20, -1));

        jLabel10.setText("Y");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 90, 10, -1));

        jLabel11.setText("Y");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 120, 20, -1));

        jLabel12.setText("X, Y");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 160, -1, -1));

        jLabel13.setText("+");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 130, -1, -1));
        add(txtRZ1, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 90, 50, -1));
        add(txtRZ2, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 120, 50, -1));

        jLabel14.setText("+");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, 20, -1));

        jLabel15.setText("+");
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 70, 20, -1));

        btnLimpiar.setText("LIMPIAR");
        add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, -1, -1));

        btnResolver.setText("RESOLVER");
        add(btnResolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Variables básicas", "Ecuación", "X1", "X2", "X3", "X4", "X5", "Lado derecho"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 900, 260));

        jLabel16.setText("RESPUESTA");
        add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 510, -1, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 540, 130, -1));

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane3.setViewportView(jTextArea2);

        add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 540, 130, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void txtEX1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEX1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEX1ActionPerformed

    private void txtRS3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRS3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRS3ActionPerformed

    private void txtRS2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRS2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRS2ActionPerformed

    private void txtRY1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRY1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRY1ActionPerformed

    private void txtRS1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRS1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRS1ActionPerformed

    private void txtRZ3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRZ3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRZ3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnResolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField txtEX1;
    private javax.swing.JTextField txtEX2;
    private javax.swing.JTextField txtRS1;
    private javax.swing.JTextField txtRS2;
    private javax.swing.JTextField txtRS3;
    private javax.swing.JTextField txtRX1;
    private javax.swing.JTextField txtRX2;
    private javax.swing.JTextField txtRY1;
    private javax.swing.JTextField txtRY2;
    private javax.swing.JTextField txtRZ1;
    private javax.swing.JTextField txtRZ2;
    private javax.swing.JTextField txtRZ3;
    private javax.swing.JTextField txtX3;
    // End of variables declaration//GEN-END:variables
}
